const ACTIVE_COLOR = "#4F92F8";
const INACTIVE_COLOR = "#B1B2B2";
const SECONDARY_COLOR = "#F2F2F2";
const TEXT_PRIMARY_COLOR = "#383838";
const TEXT_SECONDARY_COLOR = "#FFFFFF";

export {
  ACTIVE_COLOR,
  INACTIVE_COLOR,
  SECONDARY_COLOR,
  TEXT_PRIMARY_COLOR,
  TEXT_SECONDARY_COLOR,
};
